### ISSUE TITLE
Invalid parameter: redirect_uri

### ISSUE THREAD

**Issue by uvijayan** [fusionfabric/ffdc-sample-retail-webapp#42]
For hackathon 2022, we are planning to use this application to enhace further for our requirement.  I have changed API refrences with preprod api.  While invoking the url http://localhost:3000 or http://hostname:3000 its thowing "Invalid Parameter :redirect_uri" error in the browser.

the URL is  :https://api.preprod.fusionfabric.cloud/login/v1/sandbox/oidc/authorize?client_id=a0d47a7e-89b8-4fc3-a19d-1ffe4ccd2b8f&scope=openid&response_type=code&redirect_uri=http%3A%2F%2FBLRL82XGVT2%3A3000%2Flogin%2Fcallback&nonce=7758c0a5-2d36-4f71-8865-4b7ea344ae47&state=7fde01ed-71d0-4b3e-abbc-747667e1484a

Please kindly let me know how to fix this error ASAP.

**Comment by dorsaffrigui** [comment]
Resolved by changing the app config on Dev portal to use a B2C api instead of B2B
